#pragma once

#include <cstdint>

namespace Handshake {
	// ============================================================
//  Packet types used during the 4-packet mutual verification
//  handshake. These are separate from the regular Packet class
//  and are only exchanged during connection establishment.
// ============================================================

// Identifies whether a verification packet is a challenge or response.
	enum class VerificationPacketType : uint32_t {
		CHALLENGE = 1U,
		RESPONSE = 2U
	};


	// Sent by either side to initiate a challenge.
	// Layout: [ Type (4) | Random (4) | CRC32 (4) ] = 12 bytes total
	#pragma pack(push, 1)
	struct ChallengePacket {
		uint32_t Type;      // Must be VerificationPacketType::CHALLENGE
		uint32_t Random;    // Random number generated by the sender
		uint32_t CRC32;     // CRC-32 computed over Type + Random (8 bytes)
	};
	#pragma pack(pop)



	// Sent in response to a challenge.
	// Signature = CRC-32 of (shared_secret_bytes + random_bytes)
	// Layout: [ Type (4) | Signature (4) | CRC32 (4) ] = 12 bytes total
	#pragma pack(push, 1)
	struct ResponsePacket
	{
		uint32_t Type;      // Must be VerificationPacketType::RESPONSE
		uint32_t Signature; // Hash(secret + random) — see Server::ComputeSignature()
		uint32_t CRC32;     // CRC-32 computed over Type + Signature (8 bytes)
	};
	#pragma pack(pop)
};